### ISSUE TITLE
Animation issue

### ISSUE THREAD

**Issue by N-G-Neer** [D3fau4/Helltaker-switch#10]
Most characters don't have that trademark Helltaker bobbing animation the original game has. They seem to be moving from their heads rather than from their legs. Animation root problem maybe ? It also affects Lucifer's glass swinging animation and the head swiveling GLORIOUS SUCCESS skeletons.

Also, the Helltaker laugh animation seems to stop sooner than on PC.

Minor nitpicks but a fix would be most appreciated ^^

**Comment by D3fau4** [comment]
if you could record or post a capture would you help me.

**Comment by N-G-Neer** [comment]
Issue 1 : Characters bobbing from the head instead of feet.
Associated file : Headbobbing.mp4
Timestamped video for reference : https://youtu.be/iybUh3-WtfE?t=37
Comment : Helltaker doesn't stay still for long in the reference video, but in my video Pandemonica illustrate the problem pretty well. Her head is stationary and her feet are swinging about.

Issue 2 : Lucifer animation jitter.
Associated file : SatanJitter.mp4
Timestamped video for reference : https://youtu.be/iybUh3-WtfE?t=307
Comment : On PC, Lucifer is perfectly still while the glass shakes. On Switch the whole sprite jitters.

Issue 2.5 : Sprite fade-in direction
Associated file : SatanJitter.mp4
Timestamped video for reference : https://youtu.be/iybUh3-WtfE?t=307
Comment : On PC, character sprites in cinematic fade in from right to left. On Switch, the fade in diagonally from up right to down left. (Skeleton guards on each side of Lucifer for example)

Issue 3 : Helltaker laugh anim stops
Associated file : HelltakerLaugh.mp4
Timestamped video for reference : https://youtu.be/iybUh3-WtfE?t=72
Comment : On PC, the Helltaker laughs and his shoulders shake up and down a few times as he does so. On Switch, he just takes a static pose.

Issue 4 : GLORIOUS SUCCESS horizontal swivel
Associated file : HorizontalSwivel.mp4
Timestamped video for reference : https://youtu.be/iybUh3-WtfE?t=1141
Comment : On PC, the GLORIOUS SUCCESS skeletons swivel their head in an almost circular fashion. The head moves both along the vertical and horizontal axis. On Switch, the head only moves horizontally. 

Issue 5 : Hidden exit prompt
Associated file : ExitError.mp4
Timestamped video for reference : N/A
Comment : When scrolling down the main menu, you can still select the original "Exit" option. Doing so will display the goodbye line and crash/close the game with an error.

Issue 6 : Background dialog skip
Associated file : BGDialogSkip.mp4
Timestamped video for reference : N/A
Comment : I don't know if this is an issue that also exists on PC but when pressing A repeatedly during the intro screens, you can advance the dialog past the main menu.

[HelltakerSwitchIssues.zip](https://github.com/D3fau4/Helltaker-switch/files/4905605/HelltakerSwitchIssues.zip)

**Comment by D3fau4** [comment]
okay i think i found the problem:

https://streamable.com/4b610c

**Comment by N-G-Neer** [comment]
Nice going ! Still the slightliest of swing on her legs but looks like you figured it out ^^
Now to do that for all the sprites D:

What was causing the issue out of curiosity ?

**Comment by D3fau4** [comment]
the pivot (the blue circle) of the sprites is set in 0.5 X and 0.5 Y

![image](https://user-images.githubusercontent.com/19638408/87224722-dd5bbe80-c387-11ea-9225-71370355c087.png)

fix:

![image](https://user-images.githubusercontent.com/19638408/87224755-12681100-c388-11ea-9d98-7982ae4f2c69.png)

You can see how i fix it here: https://youtu.be/JTo9ozSQcMs
