### ISSUE TITLE
Port not working

### ISSUE THREAD

**Issue by adachicabron** [D3fau4/Helltaker-switch#13]
I tried to open the game and it shows this message :(, what can I do?
![image](https://user-images.githubusercontent.com/68619155/88112818-e8e18d80-cbb0-11ea-9d8d-bf024fb1ae38.png)

**Comment by D3fau4** [comment]
Update sigpatches.

**Comment by adachicabron** [comment]
> Update sigpatches.

It worked thank you ♥
