### ISSUE TITLE
Language change(vita) and the language support form in the README

### ISSUE THREAD

**Issue by History-exe** [D3fau4/Helltaker-switch#20]
Sorry to interrupt you, I would like to ask if there is no language change option for the PSV version? I played the game and looked for it but didn't find it.

Also, I found that there are only traditional Chinese translations, not simplified Chinese translations. However, the language support of the README shows that Simplified Chinese is supported, while Traditional Chinese is not supported. Is this a mark error?

**Comment by D3fau4** [comment]
yes, this is an error, only CH-HANT is supported. And on PSVita I have already seen that you have liked my tweet, supposedly it should automatically choose the language of your console.
