### ISSUE TITLE
How will I download this?

### ISSUE THREAD

**Issue by cyber-qater** [D3fau4/Helltaker-switch#30]
I have no idea where to start?!

**Comment by MJr0019** [comment]
Hi,

Here:

https://github.com/D3fau4/Helltaker-switch/releases

**Comment by cyber-qater** [comment]
Didn’t work

**Comment by MJr0019** [comment]
What didn't work, which version are you trying to download?

can you give more details?

**Comment by cyber-qater** [comment]
The link did not work sadly
