### ISSUE TITLE
Wii U port ?

### ISSUE THREAD

**Issue by gameblabla** [D3fau4/Helltaker-switch#32]
There's a build of Unity 2017.1.2p3 out there for the Wii U (and if you want to get crazy, possibly even the New 3DS as well). Would be nice to get that working on there.
I do wonder how you managed to port it though, given that it is not open source ?

**Comment by D3fau4** [comment]
I cant port from 2019.4.2f1 to 2017.1.2f3 the project breaks down completely. I could only compile a broken version I made for psvita in 2017.4.2f2.

**Comment by gameblabla** [comment]
Wii U is supported on 2017.4.2f2 as well (they dropped support for it in the [2018 build](https://blog.unity.com/technology/get-early-access-to-unity-2018-1-the-beta-is-out)). Sad to hear about it being broken on vita/2017.4.2f2 though :(.... Worth a try i guess. (I'm not sure about the new 3DS but i believe it's in a later 2018 build)

**Comment by gameblabla** [comment]
So i actually decided to take a look at this personally and yeah you're right, it is seemingly only 2017.1.2f3... :/
I did manage to get a simple Unity 2017 game working on my Wii U after taking a whole day figuring it out [how to
package it in the WUP format](https://github.com/gameblabla/template-unity-wiiu-nuspacker) and have it working on real hardware...

![IMG_20230129_185752](https://user-images.githubusercontent.com/8717966/215351312-4fda2280-23fe-4a39-bcb3-88023987e6d1.jpg)

I did notice the PSVita had 2018.2.0b4 available so not sure if that's of any help for the Vita build ?
But as far as Wii U goes, that won't work... unless you're willing to backport it further :P

That's on top of other issues such as OGG not being supported (requiring the use of WAV or MP3).

Close this i guess ?
