### ISSUE TITLE
Kicks doesn't stop when button is holding

### ISSUE THREAD

**Issue by JrRadiant** [D3fau4/Helltaker-switch#4]
Hi, thank you for your great work!.. (:

Btw, I think I found out a tiny but so-o miserable bug:

Let's see: for example, at the first level (or anywhere), when you kick a rock against the wall **and don't** release the D-Pad button after the first kick, the hero _continues_ kicking it indefinitely instead of spend just 1 move and stop.

..So, the player must press the buttons super-duper VERY carefully, and, sometimes, even 0.3 sec of pressing the kick button is enough to spend 2-5 moves, instead of just one how it should be.

Here's a sample ingame video with this problem: https://streamable.com/8bur09

So, ehm, do I explained it correctly? Please feel free to ask me if it's not.

**Comment by D3fau4** [comment]
It is not an error, in the original build works same as switch.

**Comment by JrRadiant** [comment]
OK thanks!
