### ISSUE TITLE
Fallo al ver un bloque de texto

### ISSUE THREAD

**Issue by RY0M43CH1Z3N** [D3fau4/Helltaker-switch#8]
Buenas,

como se puede ver en la imagen adjunta(https://ibb.co/DpkGgX5),
al final del texto se corta la última parte y
deja el párrafo inconcluso.

¡Un saludo!

**Comment by D3fau4** [comment]
Okey arreglado en el pull request #9 de @Megaflan.

Lo añadiré el miércoles junto con el idioma alemán.

**Comment by D3fau4** [comment]
Okey arreglado.
